version: '3.4'
services:
  # react-app:
  #   image: test
  #   ports:
  #     - 4002:3000
  mongo1:
    image: mongo:4.4.27
    restart: always
    ports:
      - 27099:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_ENABLE_ADMIN : 'true'
      ME_CONFIG_MONGODB_SERVER: mongo1    
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27099/

      
