apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: login-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: my-service-back
spec:
  selector:
    app: loginback
  # env:
  #   - name: back-portname
  #     valueFrom :
  #       ConfigMapKeyRef:
  #         name: portname
  #         key: backend-port
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 80
  type: LoadBalancer